using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Enums
{
    public enum damageType
    {
        Physical,
        Magical
    }
    public enum debuffType
    {
        Slow,
        Rooted,
        WeakGrip,
        Exiled,
        Marked,
        Calm,
        BrokenGaurd,
        Burnt,
        Stun,
        Freeze,
        Cold,
        Blinded,
        Tainted,
        Sleep,
        Hungry,
        Healthy,
        UnHealthy,
        GodsAnger,
        GodsBlessing
    }
    public enum cardName
    {
        lionFirstCard,
        lionSecondCard,
        lionThirdCard,
        lionFourthCard,
        lionFifthCard,
        lionSixthCard,
        lionSeventhCard,
        lionEighthCard,
        lionNinthCard,
        crocodileFirstCard,
        crocodileSecondCard,
        crocodileThirdCard,
        crocodileFourthCard,
        crocodileFifthCard,
        crocodileSixthCard,
        crocodileSeventhCard,
        crocodileEighthCard,
        crocodileNinthCard,
        fishFirstCard,
        fishSecondCard,
        fishThirdCard,
        fishFourthCard,
        fishFifthCard,
        fishSixthCard,
        fishSeventhCard,
        fishEighthCard,
        fishNinthCard,
        salamanderFirstCard,
        salamanderSecondCard,
        salamanderThirdCard,
        salamanderFourthCard,
        salamanderFifthCard,
        salamanderSixthCard,
        salamanderSeventhCard,
        salamanderEighthCard,
        salamanderNinthCard,
        frogFirstCard,
        frogSecondCard,
        frogThirdCard,
        frogFourthCard,
        frogFifthCard,
        frogSixthCard,
        frogSeventhCard,
        frogEighthCard,
        frogNinthCard,
        tritonFirstCard,
        tritonSecondCard,
        tritonThirdCard,
        tritonFourthCard,
        tritonFifthCard,
        tritonSixthCard,
        tritonSeventhCard,
        tritonEighthCard,
        tritonNinthCard,
    }
}